stages:
  - build
  - release

variables:
  GIT_STRATEGY: clone
  ELECTRON_BUILDER_CACHE: "/root/.cache/electron-builder"

build_app:
  image: electronuserland/builder:wine # Menggunakan image dengan Wine untuk build Windows
  stage: build
  script:
    - echo "NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL" > renderer/.env.local
    - echo "GITLAB_PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN" > renderer/.env.local
    - yarn install --frozen-lockfile
    - yarn nextron build --win --ia32 --x64 # Build langsung dengan electron-builder
    - ls -lah dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

release:
  image: electronuserland/builder:wine
  stage: release
  script:
    - echo "NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL" > renderer/.env.local
    - echo "GITLAB_PERSONAL_ACCESS_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN" > renderer/.env.local
    - export GITLAB_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
    - yarn install --frozen-lockfile
    - yarn nextron build --win --ia32 --x64 --publish never # Publish ke GitLab Releases
    - ls -lah dist/
    - |
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_PERSONAL_ACCESS_TOKEN" \
      --form "name=EXPOS-V${CI_COMMIT_TAG}.exe" \
      --form "url=https://gitlab.com/api/v4/projects/42994318/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/dist/EXPOS-V${CI_COMMIT_TAG}.exe?job=release" \
      --form "filepath=/EXPOS-V${CI_COMMIT_TAG}.exe" \
      --form "link_type=other" \
      "https://gitlab.com/api/v4/projects/42994318/releases"

  artifacts:
    paths:
      - dist/
  only:
    - tags
