stages:
  - build
  - release

variables:
  GIT_STRATEGY: clone
  ELECTRON_BUILDER_CACHE: "/root/.cache/electron-builder"

build_app:
  image: electronuserland/builder:wine  # Menggunakan image dengan Wine untuk build Windows
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn nextron build --win --ia32 --x64  # Build langsung dengan electron-builder
  artifacts:
    paths:
      - dist/

release:
  image: electronuserland/builder:wine
  stage: release
  script:
    - export GITLAB_TOKEN=$GITLAB_PERSONAL_ACCESS_TOKEN
    - yarn install --frozen-lockfile
    - yarn nextron build --win --ia32 --x64 --publish always  # Publish ke GitLab Releases
  only:
    - main
